
export const LOG = 100


// OBJECT/GENERAL
export const GET_OBJECT_ID_BY_NAME = 1000
export const CREATE_PRIMITIVE_OBJECT = 1001
export const SET_OBJECT_POSITION = 1100
export const GET_OBJECT_POSITION = 1101
export const SET_OBJECT_ROTATION = 1110
export const GET_OBJECT_ROTATION = 1111
export const SET_OBJECT_SCALE = 1120
export const GET_OBJECT_SCALE = 1121
export const SET_OBJECT_NAME = 1130
export const GET_OBJECT_NAME = 1131

// OBJECT/MATERIAL
export const GET_MATERIAL_OF_OBJECT = 1200
// OBJECT/EVENT
export const SET_OBJECT_EVENT_LISTENER = 1300

// MATERIAL/GENERAL
export const GET_MATERIAL_ID_BY_NAME = 2000
// MATERIAL/COLOR
export const SET_MATERIAL_COLOR = 2100

// Loader
export const LOAD_GLTF = 3000
export const LOAD_GLTF_ON_PROGRESS = 3001
export const LOAD_GLTF_ON_COMPLETE = 3002

export const LOAD_SKY = 4000

// FROM Sandbox
export const SANDBOX_ON_OBJECT_EVENT = 10000
export const SANDBOX_ON_GLTF_LOADED = 10010
export const SANDBOX_ON_SKY_LOADED = 10020