env:
  node: true
  es2021: true

extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  indent: ["error", 2, {
    FunctionDeclaration: {
      parameters: 1,
    }
  }],
  "function-paren-newline": ["error", "never"],
  "no-multiple-empty-lines": ["error", {"max": 0}]
}
