name: Packer test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  all:
    name: Tests code
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: packer
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: t
        run: ls
      - name: Install npm modules
        run: yarn install
      - name: Run tests
        run: yarn test
